'use client'
import {useState} from 'react';
import CustomSlider from '@/components/Slider/Slider';
import './product.scss';
import Link from 'next/link';
import Slider from 'react-slick';
import ServiceProductSlider from '@/components/ServiceProductSlider/ServiceProductSlider';
import Head from 'next/head';


type Props = {
  params: {
    id: string
  }
}

type Product = {
  slider: string[],
  title: string,
  description: string,
  options: string[],
  scopeOfDelivery: string[]
}


const data: Product[] = [
  
  // {
  //   slider: ['/product/fittings_for_building_new_cars_series_779/1.webp', '/product/fittings_for_building_new_cars_series_779/2.webp','/product/fittings_for_building_new_cars_series_779/3.webp','/product/fittings_for_building_new_cars_series_779/4.webp','/product/fittings_for_building_new_cars_series_779/5.webp','/product/fittings_for_building_new_cars_series_779/6.webp','/product/fittings_for_building_new_cars_series_779/7.webp','/product/fittings_for_building_new_cars_series_779/8.webp','/product/fittings_for_building_new_cars_series_779/9.webp','/product/fittings_for_building_new_cars_series_779/10.webp'],
  //   title: 'Fittings for capital and restored repair cars series 47k',
  //   description: 'The key direction of LLC “A.T.O.R.” development is a manufacture and supply of components for passenger rail cars. In the company’s arsenal as a classic option, as well as its own development of enhanced functionality. We offer to use the services of delivery of components for major repairs of cars of the series 47K. There are two possible options – standard and a car with furniture, which transforms at night. The standard equipment is different in terms of completeness and high quality, for cars with transformed furniture, we have developed and implemented a number of innovative solutions that can significantly improve the comfort of passengers and drivers.',
  //   options: ['47K – compartment wagon;', '47K – compartment wagon with furniture, which transforms at night'],
  //   scopeOfDelivery: ['Set of fire protection of heating pipes', 'Wagon wall set', 'A set of wagon ceilings', 'A set of furniture for the service compartment of a wagon', 'Set toilet elements', 'Wagon wall set', 'A set of furniture for the service compartment of a wagon']
  // },

  {
    slider: ['/product/fittings_for_building_new_cars_series_779/1.webp', '/product/fittings_for_building_new_cars_series_779/2.webp','/product/fittings_for_building_new_cars_series_779/3.webp','/product/fittings_for_building_new_cars_series_779/4.webp','/product/fittings_for_building_new_cars_series_779/5.webp','/product/fittings_for_building_new_cars_series_779/6.webp','/product/fittings_for_building_new_cars_series_779/7.webp','/product/fittings_for_building_new_cars_series_779/8.webp','/product/fittings_for_building_new_cars_series_779/9.webp','/product/fittings_for_building_new_cars_series_779/10.webp'],
    title: 'Fittings for Building New Cars Series 779',
    description: 'LCC “A.T.O.R.” offers to use services in the field of supply of components for the construction of new cars series 779. In the production process, we use only quality certified materials and the latest technologies. The capabilities of the company allow us to fit new cars in accordance with the standards of comfort and safety. Set of fire protection of heating pipes Enclosures are made of stainless steel, equipped with chrome locks and fastening elements. Differ from aesthetic attractiveness and long lifetime; The set of walls of the car The kit includes lightweight internal partitions, facing hard-plastics with the use of cellular aluminum filler. The color of materials is selected in agreement with the customer; A set of carriage ceilings The set includes lightweight frameless non-flammable ceilings made of sheet material, painted with powder paint. It is possible to manufacture ceiling panels of fiberglass. The color of materials is selected in agreement with the customer; A set of furniture for the service compartment of a wagon The kit includes everything necessary for the service compartment: a refrigerator cabinet, a dishwasher, a wardrobe with a stainless steel sink, a comfortable armchair for the conductor. Set of toilet elements The set includes: sinks made of fiberglass with mirrors and fittings, stainless steel sinks, fiberglass floors Set of elements of the corridor The set includes a set of handrails made of durable stainless steel, coated with powder paint; A set of interior and exterior doors, which includes: 12 doors for a passenger compartment and a pavilion for the rest of the drivers, equipped with a special mechanism that provides smooth, silent opening and closing, reliable fixing in extreme positions and complete locking; 2 doors of the toilet equipped with an electromobiling lock; 1 fireproof door of passenger compartment with the possibility of fixing in an open position; 2 doors from the vestibule to the carriage (left and right); Set of facing of side walls The facade of the side walls is made of high quality fiberglass, the color is selected in agreement with the customer; A set of furniture for passenger compartments, which includes: lower and upper sleeping shelves with fixing elements for fixing in extreme positions, covered with heavier fabrics, the color of which is selected in agreement with the customer; tables with the possibility of automatic fixing in extreme positions; stairs for upper shelves; luggage racks; accessories: handrails, holders for trousers, newspapers, hooks, etc.',
    options: ['61-779 — compartment wagon', '47K — compartment wagon with furniture, which transforms at night'],
    scopeOfDelivery: ['Set of fire protection of heating pipes', 'Wagon wall set', 'A set of wagon ceilings', 'A set of furniture for the service compartment of a wagon', 'Set toilet elements', 'Wagon wall set', 'A set of furniture for the service compartment of a wagon']
  },
  {
    slider: ['/product/fittings_for_building_new_cars_series_779/1.webp', '/product/fittings_for_building_new_cars_series_779/2.webp','/product/fittings_for_building_new_cars_series_779/3.webp','/product/fittings_for_building_new_cars_series_779/4.webp','/product/fittings_for_building_new_cars_series_779/5.webp','/product/fittings_for_building_new_cars_series_779/6.webp','/product/fittings_for_building_new_cars_series_779/7.webp','/product/fittings_for_building_new_cars_series_779/8.webp','/product/fittings_for_building_new_cars_series_779/9.webp','/product/fittings_for_building_new_cars_series_779/10.webp'],
    title: 'Fittings for Building New Cars Series 779',
    description: 'LCC “A.T.O.R.” offers to use services in the field of supply of components for the construction of new cars series 779. In the production process, we use only quality certified materials and the latest technologies. The capabilities of the company allow us to fit new cars in accordance with the standards of comfort and safety. Set of fire protection of heating pipes Enclosures are made of stainless steel, equipped with chrome locks and fastening elements. Differ from aesthetic attractiveness and long lifetime; The set of walls of the car The kit includes lightweight internal partitions, facing hard-plastics with the use of cellular aluminum filler. The color of materials is selected in agreement with the customer; A set of carriage ceilings The set includes lightweight frameless non-flammable ceilings made of sheet material, painted with powder paint. It is possible to manufacture ceiling panels of fiberglass. The color of materials is selected in agreement with the customer; A set of furniture for the service compartment of a wagon The kit includes everything necessary for the service compartment: a refrigerator cabinet, a dishwasher, a wardrobe with a stainless steel sink, a comfortable armchair for the conductor. Set of toilet elements The set includes: sinks made of fiberglass with mirrors and fittings, stainless steel sinks, fiberglass floors Set of elements of the corridor The set includes a set of handrails made of durable stainless steel, coated with powder paint; A set of interior and exterior doors, which includes: 12 doors for a passenger compartment and a pavilion for the rest of the drivers, equipped with a special mechanism that provides smooth, silent opening and closing, reliable fixing in extreme positions and complete locking; 2 doors of the toilet equipped with an electromobiling lock; 1 fireproof door of passenger compartment with the possibility of fixing in an open position; 2 doors from the vestibule to the carriage (left and right); Set of facing of side walls The facade of the side walls is made of high quality fiberglass, the color is selected in agreement with the customer; A set of furniture for passenger compartments, which includes: lower and upper sleeping shelves with fixing elements for fixing in extreme positions, covered with heavier fabrics, the color of which is selected in agreement with the customer; tables with the possibility of automatic fixing in extreme positions; stairs for upper shelves; luggage racks; accessories: handrails, holders for trousers, newspapers, hooks, etc.',
    options: ['61-779 — compartment wagon', '47K — compartment wagon with furniture, which transforms at night'],
    scopeOfDelivery: ['Set of fire protection of heating pipes', 'Wagon wall set', 'A set of wagon ceilings', 'A set of furniture for the service compartment of a wagon', 'Set toilet elements', 'Wagon wall set', 'A set of furniture for the service compartment of a wagon']
  },
  {
    slider: ['/product/fittings_for_building_new_cars_series_779/1.webp', '/product/fittings_for_building_new_cars_series_779/2.webp','/product/fittings_for_building_new_cars_series_779/3.webp','/product/fittings_for_building_new_cars_series_779/4.webp','/product/fittings_for_building_new_cars_series_779/5.webp','/product/fittings_for_building_new_cars_series_779/6.webp','/product/fittings_for_building_new_cars_series_779/7.webp','/product/fittings_for_building_new_cars_series_779/8.webp','/product/fittings_for_building_new_cars_series_779/9.webp','/product/fittings_for_building_new_cars_series_779/10.webp'],
    title: 'Fittings for Building New Cars Series 779',
    description: 'LCC “A.T.O.R.” offers to use services in the field of supply of components for the construction of new cars series 779. In the production process, we use only quality certified materials and the latest technologies. The capabilities of the company allow us to fit new cars in accordance with the standards of comfort and safety. Set of fire protection of heating pipes Enclosures are made of stainless steel, equipped with chrome locks and fastening elements. Differ from aesthetic attractiveness and long lifetime; The set of walls of the car The kit includes lightweight internal partitions, facing hard-plastics with the use of cellular aluminum filler. The color of materials is selected in agreement with the customer; A set of carriage ceilings The set includes lightweight frameless non-flammable ceilings made of sheet material, painted with powder paint. It is possible to manufacture ceiling panels of fiberglass. The color of materials is selected in agreement with the customer; A set of furniture for the service compartment of a wagon The kit includes everything necessary for the service compartment: a refrigerator cabinet, a dishwasher, a wardrobe with a stainless steel sink, a comfortable armchair for the conductor. Set of toilet elements The set includes: sinks made of fiberglass with mirrors and fittings, stainless steel sinks, fiberglass floors Set of elements of the corridor The set includes a set of handrails made of durable stainless steel, coated with powder paint; A set of interior and exterior doors, which includes: 12 doors for a passenger compartment and a pavilion for the rest of the drivers, equipped with a special mechanism that provides smooth, silent opening and closing, reliable fixing in extreme positions and complete locking; 2 doors of the toilet equipped with an electromobiling lock; 1 fireproof door of passenger compartment with the possibility of fixing in an open position; 2 doors from the vestibule to the carriage (left and right); Set of facing of side walls The facade of the side walls is made of high quality fiberglass, the color is selected in agreement with the customer; A set of furniture for passenger compartments, which includes: lower and upper sleeping shelves with fixing elements for fixing in extreme positions, covered with heavier fabrics, the color of which is selected in agreement with the customer; tables with the possibility of automatic fixing in extreme positions; stairs for upper shelves; luggage racks; accessories: handrails, holders for trousers, newspapers, hooks, etc.',
    options: ['61-779 — compartment wagon', '47K — compartment wagon with furniture, which transforms at night'],
    scopeOfDelivery: ['Set of fire protection of heating pipes', 'Wagon wall set', 'A set of wagon ceilings', 'A set of furniture for the service compartment of a wagon', 'Set toilet elements', 'Wagon wall set', 'A set of furniture for the service compartment of a wagon']
  },
  {
    slider: ['/product/fittings_for_building_new_cars_series_779/1.webp', '/product/fittings_for_building_new_cars_series_779/2.webp','/product/fittings_for_building_new_cars_series_779/3.webp','/product/fittings_for_building_new_cars_series_779/4.webp','/product/fittings_for_building_new_cars_series_779/5.webp','/product/fittings_for_building_new_cars_series_779/6.webp','/product/fittings_for_building_new_cars_series_779/7.webp','/product/fittings_for_building_new_cars_series_779/8.webp','/product/fittings_for_building_new_cars_series_779/9.webp','/product/fittings_for_building_new_cars_series_779/10.webp'],
    title: 'Fittings for Building New Cars Series 779',
    description: 'LCC “A.T.O.R.” offers to use services in the field of supply of components for the construction of new cars series 779. In the production process, we use only quality certified materials and the latest technologies. The capabilities of the company allow us to fit new cars in accordance with the standards of comfort and safety. Set of fire protection of heating pipes Enclosures are made of stainless steel, equipped with chrome locks and fastening elements. Differ from aesthetic attractiveness and long lifetime; The set of walls of the car The kit includes lightweight internal partitions, facing hard-plastics with the use of cellular aluminum filler. The color of materials is selected in agreement with the customer; A set of carriage ceilings The set includes lightweight frameless non-flammable ceilings made of sheet material, painted with powder paint. It is possible to manufacture ceiling panels of fiberglass. The color of materials is selected in agreement with the customer; A set of furniture for the service compartment of a wagon The kit includes everything necessary for the service compartment: a refrigerator cabinet, a dishwasher, a wardrobe with a stainless steel sink, a comfortable armchair for the conductor. Set of toilet elements The set includes: sinks made of fiberglass with mirrors and fittings, stainless steel sinks, fiberglass floors Set of elements of the corridor The set includes a set of handrails made of durable stainless steel, coated with powder paint; A set of interior and exterior doors, which includes: 12 doors for a passenger compartment and a pavilion for the rest of the drivers, equipped with a special mechanism that provides smooth, silent opening and closing, reliable fixing in extreme positions and complete locking; 2 doors of the toilet equipped with an electromobiling lock; 1 fireproof door of passenger compartment with the possibility of fixing in an open position; 2 doors from the vestibule to the carriage (left and right); Set of facing of side walls The facade of the side walls is made of high quality fiberglass, the color is selected in agreement with the customer; A set of furniture for passenger compartments, which includes: lower and upper sleeping shelves with fixing elements for fixing in extreme positions, covered with heavier fabrics, the color of which is selected in agreement with the customer; tables with the possibility of automatic fixing in extreme positions; stairs for upper shelves; luggage racks; accessories: handrails, holders for trousers, newspapers, hooks, etc.',
    options: ['61-779 — compartment wagon', '47K — compartment wagon with furniture, which transforms at night'],
    scopeOfDelivery: ['Set of fire protection of heating pipes', 'Wagon wall set', 'A set of wagon ceilings', 'A set of furniture for the service compartment of a wagon', 'Set toilet elements', 'Wagon wall set', 'A set of furniture for the service compartment of a wagon']
  },
  {
    slider: ['/product/fittings_for_building_new_cars_series_779/1.webp', '/product/fittings_for_building_new_cars_series_779/2.webp','/product/fittings_for_building_new_cars_series_779/3.webp','/product/fittings_for_building_new_cars_series_779/4.webp','/product/fittings_for_building_new_cars_series_779/5.webp','/product/fittings_for_building_new_cars_series_779/6.webp','/product/fittings_for_building_new_cars_series_779/7.webp','/product/fittings_for_building_new_cars_series_779/8.webp','/product/fittings_for_building_new_cars_series_779/9.webp','/product/fittings_for_building_new_cars_series_779/10.webp'],
    title: 'Fittings for Building New Cars Series 779',
    description: 'LCC “A.T.O.R.” offers to use services in the field of supply of components for the construction of new cars series 779. In the production process, we use only quality certified materials and the latest technologies. The capabilities of the company allow us to fit new cars in accordance with the standards of comfort and safety. Set of fire protection of heating pipes Enclosures are made of stainless steel, equipped with chrome locks and fastening elements. Differ from aesthetic attractiveness and long lifetime; The set of walls of the car The kit includes lightweight internal partitions, facing hard-plastics with the use of cellular aluminum filler. The color of materials is selected in agreement with the customer; A set of carriage ceilings The set includes lightweight frameless non-flammable ceilings made of sheet material, painted with powder paint. It is possible to manufacture ceiling panels of fiberglass. The color of materials is selected in agreement with the customer; A set of furniture for the service compartment of a wagon The kit includes everything necessary for the service compartment: a refrigerator cabinet, a dishwasher, a wardrobe with a stainless steel sink, a comfortable armchair for the conductor. Set of toilet elements The set includes: sinks made of fiberglass with mirrors and fittings, stainless steel sinks, fiberglass floors Set of elements of the corridor The set includes a set of handrails made of durable stainless steel, coated with powder paint; A set of interior and exterior doors, which includes: 12 doors for a passenger compartment and a pavilion for the rest of the drivers, equipped with a special mechanism that provides smooth, silent opening and closing, reliable fixing in extreme positions and complete locking; 2 doors of the toilet equipped with an electromobiling lock; 1 fireproof door of passenger compartment with the possibility of fixing in an open position; 2 doors from the vestibule to the carriage (left and right); Set of facing of side walls The facade of the side walls is made of high quality fiberglass, the color is selected in agreement with the customer; A set of furniture for passenger compartments, which includes: lower and upper sleeping shelves with fixing elements for fixing in extreme positions, covered with heavier fabrics, the color of which is selected in agreement with the customer; tables with the possibility of automatic fixing in extreme positions; stairs for upper shelves; luggage racks; accessories: handrails, holders for trousers, newspapers, hooks, etc.',
    options: ['61-779 — compartment wagon', '47K — compartment wagon with furniture, which transforms at night'],
    scopeOfDelivery: ['Set of fire protection of heating pipes', 'Wagon wall set', 'A set of wagon ceilings', 'A set of furniture for the service compartment of a wagon', 'Set toilet elements', 'Wagon wall set', 'A set of furniture for the service compartment of a wagon']
  },
  {
    slider: ['/product/fittings_for_building_new_cars_series_779/1.webp', '/product/fittings_for_building_new_cars_series_779/2.webp','/product/fittings_for_building_new_cars_series_779/3.webp','/product/fittings_for_building_new_cars_series_779/4.webp','/product/fittings_for_building_new_cars_series_779/5.webp','/product/fittings_for_building_new_cars_series_779/6.webp','/product/fittings_for_building_new_cars_series_779/7.webp','/product/fittings_for_building_new_cars_series_779/8.webp','/product/fittings_for_building_new_cars_series_779/9.webp','/product/fittings_for_building_new_cars_series_779/10.webp'],
    title: 'Fittings for Building New Cars Series 779',
    description: 'LCC “A.T.O.R.” offers to use services in the field of supply of components for the construction of new cars series 779. In the production process, we use only quality certified materials and the latest technologies. The capabilities of the company allow us to fit new cars in accordance with the standards of comfort and safety. Set of fire protection of heating pipes Enclosures are made of stainless steel, equipped with chrome locks and fastening elements. Differ from aesthetic attractiveness and long lifetime; The set of walls of the car The kit includes lightweight internal partitions, facing hard-plastics with the use of cellular aluminum filler. The color of materials is selected in agreement with the customer; A set of carriage ceilings The set includes lightweight frameless non-flammable ceilings made of sheet material, painted with powder paint. It is possible to manufacture ceiling panels of fiberglass. The color of materials is selected in agreement with the customer; A set of furniture for the service compartment of a wagon The kit includes everything necessary for the service compartment: a refrigerator cabinet, a dishwasher, a wardrobe with a stainless steel sink, a comfortable armchair for the conductor. Set of toilet elements The set includes: sinks made of fiberglass with mirrors and fittings, stainless steel sinks, fiberglass floors Set of elements of the corridor The set includes a set of handrails made of durable stainless steel, coated with powder paint; A set of interior and exterior doors, which includes: 12 doors for a passenger compartment and a pavilion for the rest of the drivers, equipped with a special mechanism that provides smooth, silent opening and closing, reliable fixing in extreme positions and complete locking; 2 doors of the toilet equipped with an electromobiling lock; 1 fireproof door of passenger compartment with the possibility of fixing in an open position; 2 doors from the vestibule to the carriage (left and right); Set of facing of side walls The facade of the side walls is made of high quality fiberglass, the color is selected in agreement with the customer; A set of furniture for passenger compartments, which includes: lower and upper sleeping shelves with fixing elements for fixing in extreme positions, covered with heavier fabrics, the color of which is selected in agreement with the customer; tables with the possibility of automatic fixing in extreme positions; stairs for upper shelves; luggage racks; accessories: handrails, holders for trousers, newspapers, hooks, etc.',
    options: ['61-779 — compartment wagon', '47K — compartment wagon with furniture, which transforms at night'],
    scopeOfDelivery: ['Set of fire protection of heating pipes', 'Wagon wall set', 'A set of wagon ceilings', 'A set of furniture for the service compartment of a wagon', 'Set toilet elements', 'Wagon wall set', 'A set of furniture for the service compartment of a wagon']
  },
  {
    slider: ['/product/fittings_for_building_new_cars_series_779/1.webp', '/product/fittings_for_building_new_cars_series_779/2.webp','/product/fittings_for_building_new_cars_series_779/3.webp','/product/fittings_for_building_new_cars_series_779/4.webp','/product/fittings_for_building_new_cars_series_779/5.webp','/product/fittings_for_building_new_cars_series_779/6.webp','/product/fittings_for_building_new_cars_series_779/7.webp','/product/fittings_for_building_new_cars_series_779/8.webp','/product/fittings_for_building_new_cars_series_779/9.webp','/product/fittings_for_building_new_cars_series_779/10.webp'],
    title: 'Fittings for Building New Cars Series 779',
    description: 'LCC “A.T.O.R.” offers to use services in the field of supply of components for the construction of new cars series 779. In the production process, we use only quality certified materials and the latest technologies. The capabilities of the company allow us to fit new cars in accordance with the standards of comfort and safety. Set of fire protection of heating pipes Enclosures are made of stainless steel, equipped with chrome locks and fastening elements. Differ from aesthetic attractiveness and long lifetime; The set of walls of the car The kit includes lightweight internal partitions, facing hard-plastics with the use of cellular aluminum filler. The color of materials is selected in agreement with the customer; A set of carriage ceilings The set includes lightweight frameless non-flammable ceilings made of sheet material, painted with powder paint. It is possible to manufacture ceiling panels of fiberglass. The color of materials is selected in agreement with the customer; A set of furniture for the service compartment of a wagon The kit includes everything necessary for the service compartment: a refrigerator cabinet, a dishwasher, a wardrobe with a stainless steel sink, a comfortable armchair for the conductor. Set of toilet elements The set includes: sinks made of fiberglass with mirrors and fittings, stainless steel sinks, fiberglass floors Set of elements of the corridor The set includes a set of handrails made of durable stainless steel, coated with powder paint; A set of interior and exterior doors, which includes: 12 doors for a passenger compartment and a pavilion for the rest of the drivers, equipped with a special mechanism that provides smooth, silent opening and closing, reliable fixing in extreme positions and complete locking; 2 doors of the toilet equipped with an electromobiling lock; 1 fireproof door of passenger compartment with the possibility of fixing in an open position; 2 doors from the vestibule to the carriage (left and right); Set of facing of side walls The facade of the side walls is made of high quality fiberglass, the color is selected in agreement with the customer; A set of furniture for passenger compartments, which includes: lower and upper sleeping shelves with fixing elements for fixing in extreme positions, covered with heavier fabrics, the color of which is selected in agreement with the customer; tables with the possibility of automatic fixing in extreme positions; stairs for upper shelves; luggage racks; accessories: handrails, holders for trousers, newspapers, hooks, etc.',
    options: ['61-779 — compartment wagon', '47K — compartment wagon with furniture, which transforms at night'],
    scopeOfDelivery: ['Set of fire protection of heating pipes', 'Wagon wall set', 'A set of wagon ceilings', 'A set of furniture for the service compartment of a wagon', 'Set toilet elements', 'Wagon wall set', 'A set of furniture for the service compartment of a wagon']
  },
  {
    slider: ['/product/fittings_for_building_new_cars_series_779/1.webp', '/product/fittings_for_building_new_cars_series_779/2.webp','/product/fittings_for_building_new_cars_series_779/3.webp','/product/fittings_for_building_new_cars_series_779/4.webp','/product/fittings_for_building_new_cars_series_779/5.webp','/product/fittings_for_building_new_cars_series_779/6.webp','/product/fittings_for_building_new_cars_series_779/7.webp','/product/fittings_for_building_new_cars_series_779/8.webp','/product/fittings_for_building_new_cars_series_779/9.webp','/product/fittings_for_building_new_cars_series_779/10.webp'],
    title: 'Fittings for Building New Cars Series 779',
    description: 'LCC “A.T.O.R.” offers to use services in the field of supply of components for the construction of new cars series 779. In the production process, we use only quality certified materials and the latest technologies. The capabilities of the company allow us to fit new cars in accordance with the standards of comfort and safety. Set of fire protection of heating pipes Enclosures are made of stainless steel, equipped with chrome locks and fastening elements. Differ from aesthetic attractiveness and long lifetime; The set of walls of the car The kit includes lightweight internal partitions, facing hard-plastics with the use of cellular aluminum filler. The color of materials is selected in agreement with the customer; A set of carriage ceilings The set includes lightweight frameless non-flammable ceilings made of sheet material, painted with powder paint. It is possible to manufacture ceiling panels of fiberglass. The color of materials is selected in agreement with the customer; A set of furniture for the service compartment of a wagon The kit includes everything necessary for the service compartment: a refrigerator cabinet, a dishwasher, a wardrobe with a stainless steel sink, a comfortable armchair for the conductor. Set of toilet elements The set includes: sinks made of fiberglass with mirrors and fittings, stainless steel sinks, fiberglass floors Set of elements of the corridor The set includes a set of handrails made of durable stainless steel, coated with powder paint; A set of interior and exterior doors, which includes: 12 doors for a passenger compartment and a pavilion for the rest of the drivers, equipped with a special mechanism that provides smooth, silent opening and closing, reliable fixing in extreme positions and complete locking; 2 doors of the toilet equipped with an electromobiling lock; 1 fireproof door of passenger compartment with the possibility of fixing in an open position; 2 doors from the vestibule to the carriage (left and right); Set of facing of side walls The facade of the side walls is made of high quality fiberglass, the color is selected in agreement with the customer; A set of furniture for passenger compartments, which includes: lower and upper sleeping shelves with fixing elements for fixing in extreme positions, covered with heavier fabrics, the color of which is selected in agreement with the customer; tables with the possibility of automatic fixing in extreme positions; stairs for upper shelves; luggage racks; accessories: handrails, holders for trousers, newspapers, hooks, etc.',
    options: ['61-779 — compartment wagon', '47K — compartment wagon with furniture, which transforms at night'],
    scopeOfDelivery: ['Set of fire protection of heating pipes', 'Wagon wall set', 'A set of wagon ceilings', 'A set of furniture for the service compartment of a wagon', 'Set toilet elements', 'Wagon wall set', 'A set of furniture for the service compartment of a wagon']
  },
  {
    slider: ['/product/fittings_for_building_new_cars_series_779/1.webp', '/product/fittings_for_building_new_cars_series_779/2.webp','/product/fittings_for_building_new_cars_series_779/3.webp','/product/fittings_for_building_new_cars_series_779/4.webp','/product/fittings_for_building_new_cars_series_779/5.webp','/product/fittings_for_building_new_cars_series_779/6.webp','/product/fittings_for_building_new_cars_series_779/7.webp','/product/fittings_for_building_new_cars_series_779/8.webp','/product/fittings_for_building_new_cars_series_779/9.webp','/product/fittings_for_building_new_cars_series_779/10.webp'],
    title: 'Fittings for Building New Cars Series 779',
    description: 'LCC “A.T.O.R.” offers to use services in the field of supply of components for the construction of new cars series 779. In the production process, we use only quality certified materials and the latest technologies. The capabilities of the company allow us to fit new cars in accordance with the standards of comfort and safety. Set of fire protection of heating pipes Enclosures are made of stainless steel, equipped with chrome locks and fastening elements. Differ from aesthetic attractiveness and long lifetime; The set of walls of the car The kit includes lightweight internal partitions, facing hard-plastics with the use of cellular aluminum filler. The color of materials is selected in agreement with the customer; A set of carriage ceilings The set includes lightweight frameless non-flammable ceilings made of sheet material, painted with powder paint. It is possible to manufacture ceiling panels of fiberglass. The color of materials is selected in agreement with the customer; A set of furniture for the service compartment of a wagon The kit includes everything necessary for the service compartment: a refrigerator cabinet, a dishwasher, a wardrobe with a stainless steel sink, a comfortable armchair for the conductor. Set of toilet elements The set includes: sinks made of fiberglass with mirrors and fittings, stainless steel sinks, fiberglass floors Set of elements of the corridor The set includes a set of handrails made of durable stainless steel, coated with powder paint; A set of interior and exterior doors, which includes: 12 doors for a passenger compartment and a pavilion for the rest of the drivers, equipped with a special mechanism that provides smooth, silent opening and closing, reliable fixing in extreme positions and complete locking; 2 doors of the toilet equipped with an electromobiling lock; 1 fireproof door of passenger compartment with the possibility of fixing in an open position; 2 doors from the vestibule to the carriage (left and right); Set of facing of side walls The facade of the side walls is made of high quality fiberglass, the color is selected in agreement with the customer; A set of furniture for passenger compartments, which includes: lower and upper sleeping shelves with fixing elements for fixing in extreme positions, covered with heavier fabrics, the color of which is selected in agreement with the customer; tables with the possibility of automatic fixing in extreme positions; stairs for upper shelves; luggage racks; accessories: handrails, holders for trousers, newspapers, hooks, etc.',
    options: ['61-779 — compartment wagon', '47K — compartment wagon with furniture, which transforms at night'],
    scopeOfDelivery: ['Set of fire protection of heating pipes', 'Wagon wall set', 'A set of wagon ceilings', 'A set of furniture for the service compartment of a wagon', 'Set toilet elements', 'Wagon wall set', 'A set of furniture for the service compartment of a wagon']
  },
  {
    slider: ['/product/fittings_for_building_new_cars_series_779/1.webp', '/product/fittings_for_building_new_cars_series_779/2.webp','/product/fittings_for_building_new_cars_series_779/3.webp','/product/fittings_for_building_new_cars_series_779/4.webp','/product/fittings_for_building_new_cars_series_779/5.webp','/product/fittings_for_building_new_cars_series_779/6.webp','/product/fittings_for_building_new_cars_series_779/7.webp','/product/fittings_for_building_new_cars_series_779/8.webp','/product/fittings_for_building_new_cars_series_779/9.webp','/product/fittings_for_building_new_cars_series_779/10.webp'],
    title: 'Fittings for Building New Cars Series 779',
    description: 'LCC “A.T.O.R.” offers to use services in the field of supply of components for the construction of new cars series 779. In the production process, we use only quality certified materials and the latest technologies. The capabilities of the company allow us to fit new cars in accordance with the standards of comfort and safety. Set of fire protection of heating pipes Enclosures are made of stainless steel, equipped with chrome locks and fastening elements. Differ from aesthetic attractiveness and long lifetime; The set of walls of the car The kit includes lightweight internal partitions, facing hard-plastics with the use of cellular aluminum filler. The color of materials is selected in agreement with the customer; A set of carriage ceilings The set includes lightweight frameless non-flammable ceilings made of sheet material, painted with powder paint. It is possible to manufacture ceiling panels of fiberglass. The color of materials is selected in agreement with the customer; A set of furniture for the service compartment of a wagon The kit includes everything necessary for the service compartment: a refrigerator cabinet, a dishwasher, a wardrobe with a stainless steel sink, a comfortable armchair for the conductor. Set of toilet elements The set includes: sinks made of fiberglass with mirrors and fittings, stainless steel sinks, fiberglass floors Set of elements of the corridor The set includes a set of handrails made of durable stainless steel, coated with powder paint; A set of interior and exterior doors, which includes: 12 doors for a passenger compartment and a pavilion for the rest of the drivers, equipped with a special mechanism that provides smooth, silent opening and closing, reliable fixing in extreme positions and complete locking; 2 doors of the toilet equipped with an electromobiling lock; 1 fireproof door of passenger compartment with the possibility of fixing in an open position; 2 doors from the vestibule to the carriage (left and right); Set of facing of side walls The facade of the side walls is made of high quality fiberglass, the color is selected in agreement with the customer; A set of furniture for passenger compartments, which includes: lower and upper sleeping shelves with fixing elements for fixing in extreme positions, covered with heavier fabrics, the color of which is selected in agreement with the customer; tables with the possibility of automatic fixing in extreme positions; stairs for upper shelves; luggage racks; accessories: handrails, holders for trousers, newspapers, hooks, etc.',
    options: ['61-779 — compartment wagon', '47K — compartment wagon with furniture, which transforms at night'],
    scopeOfDelivery: ['Set of fire protection of heating pipes', 'Wagon wall set', 'A set of wagon ceilings', 'A set of furniture for the service compartment of a wagon', 'Set toilet elements', 'Wagon wall set', 'A set of furniture for the service compartment of a wagon']
  },
  {
    slider: ['/product/fittings_for_building_new_cars_series_779/1.webp', '/product/fittings_for_building_new_cars_series_779/2.webp','/product/fittings_for_building_new_cars_series_779/3.webp','/product/fittings_for_building_new_cars_series_779/4.webp','/product/fittings_for_building_new_cars_series_779/5.webp','/product/fittings_for_building_new_cars_series_779/6.webp','/product/fittings_for_building_new_cars_series_779/7.webp','/product/fittings_for_building_new_cars_series_779/8.webp','/product/fittings_for_building_new_cars_series_779/9.webp','/product/fittings_for_building_new_cars_series_779/10.webp'],
    title: 'Fittings for Building New Cars Series 779',
    description: 'LCC “A.T.O.R.” offers to use services in the field of supply of components for the construction of new cars series 779. In the production process, we use only quality certified materials and the latest technologies. The capabilities of the company allow us to fit new cars in accordance with the standards of comfort and safety. Set of fire protection of heating pipes Enclosures are made of stainless steel, equipped with chrome locks and fastening elements. Differ from aesthetic attractiveness and long lifetime; The set of walls of the car The kit includes lightweight internal partitions, facing hard-plastics with the use of cellular aluminum filler. The color of materials is selected in agreement with the customer; A set of carriage ceilings The set includes lightweight frameless non-flammable ceilings made of sheet material, painted with powder paint. It is possible to manufacture ceiling panels of fiberglass. The color of materials is selected in agreement with the customer; A set of furniture for the service compartment of a wagon The kit includes everything necessary for the service compartment: a refrigerator cabinet, a dishwasher, a wardrobe with a stainless steel sink, a comfortable armchair for the conductor. Set of toilet elements The set includes: sinks made of fiberglass with mirrors and fittings, stainless steel sinks, fiberglass floors Set of elements of the corridor The set includes a set of handrails made of durable stainless steel, coated with powder paint; A set of interior and exterior doors, which includes: 12 doors for a passenger compartment and a pavilion for the rest of the drivers, equipped with a special mechanism that provides smooth, silent opening and closing, reliable fixing in extreme positions and complete locking; 2 doors of the toilet equipped with an electromobiling lock; 1 fireproof door of passenger compartment with the possibility of fixing in an open position; 2 doors from the vestibule to the carriage (left and right); Set of facing of side walls The facade of the side walls is made of high quality fiberglass, the color is selected in agreement with the customer; A set of furniture for passenger compartments, which includes: lower and upper sleeping shelves with fixing elements for fixing in extreme positions, covered with heavier fabrics, the color of which is selected in agreement with the customer; tables with the possibility of automatic fixing in extreme positions; stairs for upper shelves; luggage racks; accessories: handrails, holders for trousers, newspapers, hooks, etc.',
    options: ['61-779 — compartment wagon', '47K — compartment wagon with furniture, which transforms at night'],
    scopeOfDelivery: ['Set of fire protection of heating pipes', 'Wagon wall set', 'A set of wagon ceilings', 'A set of furniture for the service compartment of a wagon', 'Set toilet elements', 'Wagon wall set', 'A set of furniture for the service compartment of a wagon']
  },
];



// export function generateMetadata({params: {id}}: Props) {

  
//   return {
//     title: id
//   }
// }

export default function ProductPage({params: {id}}: Props) {
  const [productSlide, setProductSlide] = useState(0);
  const [readMore, setReadMore] = useState(false);
  const currentProduct = data.filter((item, i) => i === +id)[0]
  const {slider, title, description, options, scopeOfDelivery} = currentProduct;

  const createList = (options: string[]) => {
    return options.map((item, i) => {
      return (
        <li className="product__container-info-container-list-item" key={i}>
          {item}
        </li>
      )
    })
  }

  return (
    <>
      <Head>
        <title>test</title>
        
      </Head>
      <div className="product">
        <CustomSlider data={slider}/>
    
        <div className="product__container">
          <span className='product__container-title'>Products</span>

          <div className="product__container-info">
            <h2 className="product__container-info-title">{title}</h2>
            <div className="product__container-info-container">
              <p className="product__container-info-container-text" 
                style={!readMore? {
                  // maxHeight: '250px',
                   transition: 'all .3s'} : {maxHeight: '2000px', transition: 'all .3s'}}
              >
                {readMore ? description : `${description.slice(0, 421)}...`}
              </p>
              <button 
                className="product__container-info-container-button" 
                onClick={() => setReadMore(!readMore)}><span>{readMore ? '-' : '+'}</span> Read More</button>
              <h3 className="product__container-info-container-title">Options:</h3>
              <ul className="product__container-info-container-list">
                {createList(options)}
              </ul>
              <h3 className="product__container-info-container-title">Scope of Delivery:</h3>
              <ul className="product__container-info-container-list">
                {createList(scopeOfDelivery)}
              </ul>

            </div>
          </div>
        </div>

        <ServiceProductSlider status={true}/>

      </div>
    </>
    
  )
}